;
; https://projecteuler.net/problem=2
;
; Problem 2 - Even Fibonacci numbers
;
;     Each new term in the Fibonacci sequence is generated by adding the
;     previous two terms. By starting with 1 and 2, the first 10 terms will be:
;
;         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;     By considering the terms in the Fibonacci sequence whose values do not
;     exceed four million, find the sum of the even-valued terms.
;

(use gauche.test)

(define main (lambda (arguments)
    (print (sum-of-even-valued-fibonacci-numbers (- 4000000 1)))))

(define unit-test (lambda()
    (test-start "sum-of-even-valued-fibonacci-numbers")
    (test* "call by 1" 0 (sum-of-even-valued-fibonacci-numbers 1))
    (test* "call by 2" 2 (sum-of-even-valued-fibonacci-numbers 2))
    (test* "call by 3" 2 (sum-of-even-valued-fibonacci-numbers 3))
    (test* "call by 5" 2 (sum-of-even-valued-fibonacci-numbers 5))
    (test* "call by 8" 10 (sum-of-even-valued-fibonacci-numbers 8))
    (test* "call by 13" 10 (sum-of-even-valued-fibonacci-numbers 13))
    (test* "call by 21" 10 (sum-of-even-valued-fibonacci-numbers 21))
    (test* "call by 34" 44 (sum-of-even-valued-fibonacci-numbers 34))
    (test* "call by 55" 44 (sum-of-even-valued-fibonacci-numbers 55))
    (test* "call by 89" 44 (sum-of-even-valued-fibonacci-numbers 89))
    (test-end)))

(define sum-of-even-valued-fibonacci-numbers (lambda (maximum-value)
    (define sum-of-even-valued-fibonacci-numbers (lambda (current-value next-value maximum-value sum)
        (cond
            ((> current-value maximum-value)
                sum)
            ((even? current-value)
                (sum-of-even-valued-fibonacci-numbers
                    next-value
                    (+ current-value next-value)
                    maximum-value
                    (+ sum current-value)))
            (else
                (sum-of-even-valued-fibonacci-numbers
                    next-value
                    (+ current-value next-value)
                    maximum-value
                    sum)))))
    (sum-of-even-valued-fibonacci-numbers 1 2 maximum-value 0)))

